package com.login.db.model.server;

public class Server {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.id
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.areaId
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer areaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.serverName
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private String servername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.isDeleted
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.ip
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.port
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.areaName
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private String areaname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.conditionSet
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private String conditionset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.isActive
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer isactive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.status
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.httpport
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Integer httpport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.secritKey
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private String secritkey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.addtime
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Long addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.opentime
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	private Long opentime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.id
	 * @return  the value of cs_server.id
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.id
	 * @param id  the value for cs_server.id
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.areaId
	 * @return  the value of cs_server.areaId
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getAreaid() {
		return areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.areaId
	 * @param areaid  the value for cs_server.areaId
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setAreaid(Integer areaid) {
		this.areaid = areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.serverName
	 * @return  the value of cs_server.serverName
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public String getServername() {
		return servername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.serverName
	 * @param servername  the value for cs_server.serverName
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setServername(String servername) {
		this.servername = servername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.isDeleted
	 * @return  the value of cs_server.isDeleted
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.isDeleted
	 * @param isdeleted  the value for cs_server.isDeleted
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.ip
	 * @return  the value of cs_server.ip
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.ip
	 * @param ip  the value for cs_server.ip
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.port
	 * @return  the value of cs_server.port
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.port
	 * @param port  the value for cs_server.port
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.areaName
	 * @return  the value of cs_server.areaName
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public String getAreaname() {
		return areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.areaName
	 * @param areaname  the value for cs_server.areaName
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.conditionSet
	 * @return  the value of cs_server.conditionSet
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public String getConditionset() {
		return conditionset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.conditionSet
	 * @param conditionset  the value for cs_server.conditionSet
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setConditionset(String conditionset) {
		this.conditionset = conditionset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.isActive
	 * @return  the value of cs_server.isActive
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getIsactive() {
		return isactive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.isActive
	 * @param isactive  the value for cs_server.isActive
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setIsactive(Integer isactive) {
		this.isactive = isactive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.status
	 * @return  the value of cs_server.status
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.status
	 * @param status  the value for cs_server.status
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.httpport
	 * @return  the value of cs_server.httpport
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Integer getHttpport() {
		return httpport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.httpport
	 * @param httpport  the value for cs_server.httpport
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setHttpport(Integer httpport) {
		this.httpport = httpport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.secritKey
	 * @return  the value of cs_server.secritKey
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public String getSecritkey() {
		return secritkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.secritKey
	 * @param secritkey  the value for cs_server.secritKey
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setSecritkey(String secritkey) {
		this.secritkey = secritkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.addtime
	 * @return  the value of cs_server.addtime
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Long getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.addtime
	 * @param addtime  the value for cs_server.addtime
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setAddtime(Long addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.opentime
	 * @return  the value of cs_server.opentime
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Long getOpentime() {
		return opentime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.opentime
	 * @param opentime  the value for cs_server.opentime
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setOpentime(Long opentime) {
		this.opentime = opentime;
	}
}