package com.login.db.model.server;

import com.login.db.model.server.Server;
import com.login.db.model.server.ServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int countByExample(ServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int deleteByExample(ServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int insert(Server record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int insertSelective(Server record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	List<Server> selectByExample(ServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	Server selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Server record, @Param("example") ServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int updateByExample(@Param("record") Server record, @Param("example") ServerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int updateByPrimaryKeySelective(Server record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	int updateByPrimaryKey(Server record);
}