package com.login.db.model.server;

import java.util.ArrayList;
import java.util.List;

public class ServerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public ServerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAreaidIsNull() {
			addCriterion("areaId is null");
			return (Criteria) this;
		}

		public Criteria andAreaidIsNotNull() {
			addCriterion("areaId is not null");
			return (Criteria) this;
		}

		public Criteria andAreaidEqualTo(Integer value) {
			addCriterion("areaId =", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotEqualTo(Integer value) {
			addCriterion("areaId <>", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidGreaterThan(Integer value) {
			addCriterion("areaId >", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidGreaterThanOrEqualTo(Integer value) {
			addCriterion("areaId >=", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidLessThan(Integer value) {
			addCriterion("areaId <", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidLessThanOrEqualTo(Integer value) {
			addCriterion("areaId <=", value, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidIn(List<Integer> values) {
			addCriterion("areaId in", values, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotIn(List<Integer> values) {
			addCriterion("areaId not in", values, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidBetween(Integer value1, Integer value2) {
			addCriterion("areaId between", value1, value2, "areaid");
			return (Criteria) this;
		}

		public Criteria andAreaidNotBetween(Integer value1, Integer value2) {
			addCriterion("areaId not between", value1, value2, "areaid");
			return (Criteria) this;
		}

		public Criteria andServernameIsNull() {
			addCriterion("serverName is null");
			return (Criteria) this;
		}

		public Criteria andServernameIsNotNull() {
			addCriterion("serverName is not null");
			return (Criteria) this;
		}

		public Criteria andServernameEqualTo(String value) {
			addCriterion("serverName =", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameNotEqualTo(String value) {
			addCriterion("serverName <>", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameGreaterThan(String value) {
			addCriterion("serverName >", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameGreaterThanOrEqualTo(String value) {
			addCriterion("serverName >=", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameLessThan(String value) {
			addCriterion("serverName <", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameLessThanOrEqualTo(String value) {
			addCriterion("serverName <=", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameLike(String value) {
			addCriterion("serverName like", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameNotLike(String value) {
			addCriterion("serverName not like", value, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameIn(List<String> values) {
			addCriterion("serverName in", values, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameNotIn(List<String> values) {
			addCriterion("serverName not in", values, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameBetween(String value1, String value2) {
			addCriterion("serverName between", value1, value2, "servername");
			return (Criteria) this;
		}

		public Criteria andServernameNotBetween(String value1, String value2) {
			addCriterion("serverName not between", value1, value2, "servername");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("isDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("isDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Integer value) {
			addCriterion("isDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Integer value) {
			addCriterion("isDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Integer value) {
			addCriterion("isDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Integer value) {
			addCriterion("isDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Integer value) {
			addCriterion("isDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Integer value) {
			addCriterion("isDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Integer> values) {
			addCriterion("isDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Integer> values) {
			addCriterion("isDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Integer value1, Integer value2) {
			addCriterion("isDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Integer value1, Integer value2) {
			addCriterion("isDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andPortIsNull() {
			addCriterion("port is null");
			return (Criteria) this;
		}

		public Criteria andPortIsNotNull() {
			addCriterion("port is not null");
			return (Criteria) this;
		}

		public Criteria andPortEqualTo(Integer value) {
			addCriterion("port =", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotEqualTo(Integer value) {
			addCriterion("port <>", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThan(Integer value) {
			addCriterion("port >", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThanOrEqualTo(Integer value) {
			addCriterion("port >=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThan(Integer value) {
			addCriterion("port <", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThanOrEqualTo(Integer value) {
			addCriterion("port <=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortIn(List<Integer> values) {
			addCriterion("port in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotIn(List<Integer> values) {
			addCriterion("port not in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortBetween(Integer value1, Integer value2) {
			addCriterion("port between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotBetween(Integer value1, Integer value2) {
			addCriterion("port not between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andAreanameIsNull() {
			addCriterion("areaName is null");
			return (Criteria) this;
		}

		public Criteria andAreanameIsNotNull() {
			addCriterion("areaName is not null");
			return (Criteria) this;
		}

		public Criteria andAreanameEqualTo(String value) {
			addCriterion("areaName =", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotEqualTo(String value) {
			addCriterion("areaName <>", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameGreaterThan(String value) {
			addCriterion("areaName >", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameGreaterThanOrEqualTo(String value) {
			addCriterion("areaName >=", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameLessThan(String value) {
			addCriterion("areaName <", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameLessThanOrEqualTo(String value) {
			addCriterion("areaName <=", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameLike(String value) {
			addCriterion("areaName like", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotLike(String value) {
			addCriterion("areaName not like", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameIn(List<String> values) {
			addCriterion("areaName in", values, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotIn(List<String> values) {
			addCriterion("areaName not in", values, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameBetween(String value1, String value2) {
			addCriterion("areaName between", value1, value2, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotBetween(String value1, String value2) {
			addCriterion("areaName not between", value1, value2, "areaname");
			return (Criteria) this;
		}

		public Criteria andConditionsetIsNull() {
			addCriterion("conditionSet is null");
			return (Criteria) this;
		}

		public Criteria andConditionsetIsNotNull() {
			addCriterion("conditionSet is not null");
			return (Criteria) this;
		}

		public Criteria andConditionsetEqualTo(String value) {
			addCriterion("conditionSet =", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetNotEqualTo(String value) {
			addCriterion("conditionSet <>", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetGreaterThan(String value) {
			addCriterion("conditionSet >", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetGreaterThanOrEqualTo(String value) {
			addCriterion("conditionSet >=", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetLessThan(String value) {
			addCriterion("conditionSet <", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetLessThanOrEqualTo(String value) {
			addCriterion("conditionSet <=", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetLike(String value) {
			addCriterion("conditionSet like", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetNotLike(String value) {
			addCriterion("conditionSet not like", value, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetIn(List<String> values) {
			addCriterion("conditionSet in", values, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetNotIn(List<String> values) {
			addCriterion("conditionSet not in", values, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetBetween(String value1, String value2) {
			addCriterion("conditionSet between", value1, value2, "conditionset");
			return (Criteria) this;
		}

		public Criteria andConditionsetNotBetween(String value1, String value2) {
			addCriterion("conditionSet not between", value1, value2, "conditionset");
			return (Criteria) this;
		}

		public Criteria andIsactiveIsNull() {
			addCriterion("isActive is null");
			return (Criteria) this;
		}

		public Criteria andIsactiveIsNotNull() {
			addCriterion("isActive is not null");
			return (Criteria) this;
		}

		public Criteria andIsactiveEqualTo(Integer value) {
			addCriterion("isActive =", value, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveNotEqualTo(Integer value) {
			addCriterion("isActive <>", value, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveGreaterThan(Integer value) {
			addCriterion("isActive >", value, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveGreaterThanOrEqualTo(Integer value) {
			addCriterion("isActive >=", value, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveLessThan(Integer value) {
			addCriterion("isActive <", value, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveLessThanOrEqualTo(Integer value) {
			addCriterion("isActive <=", value, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveIn(List<Integer> values) {
			addCriterion("isActive in", values, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveNotIn(List<Integer> values) {
			addCriterion("isActive not in", values, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveBetween(Integer value1, Integer value2) {
			addCriterion("isActive between", value1, value2, "isactive");
			return (Criteria) this;
		}

		public Criteria andIsactiveNotBetween(Integer value1, Integer value2) {
			addCriterion("isActive not between", value1, value2, "isactive");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andHttpportIsNull() {
			addCriterion("httpport is null");
			return (Criteria) this;
		}

		public Criteria andHttpportIsNotNull() {
			addCriterion("httpport is not null");
			return (Criteria) this;
		}

		public Criteria andHttpportEqualTo(Integer value) {
			addCriterion("httpport =", value, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportNotEqualTo(Integer value) {
			addCriterion("httpport <>", value, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportGreaterThan(Integer value) {
			addCriterion("httpport >", value, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportGreaterThanOrEqualTo(Integer value) {
			addCriterion("httpport >=", value, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportLessThan(Integer value) {
			addCriterion("httpport <", value, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportLessThanOrEqualTo(Integer value) {
			addCriterion("httpport <=", value, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportIn(List<Integer> values) {
			addCriterion("httpport in", values, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportNotIn(List<Integer> values) {
			addCriterion("httpport not in", values, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportBetween(Integer value1, Integer value2) {
			addCriterion("httpport between", value1, value2, "httpport");
			return (Criteria) this;
		}

		public Criteria andHttpportNotBetween(Integer value1, Integer value2) {
			addCriterion("httpport not between", value1, value2, "httpport");
			return (Criteria) this;
		}

		public Criteria andSecritkeyIsNull() {
			addCriterion("secritKey is null");
			return (Criteria) this;
		}

		public Criteria andSecritkeyIsNotNull() {
			addCriterion("secritKey is not null");
			return (Criteria) this;
		}

		public Criteria andSecritkeyEqualTo(String value) {
			addCriterion("secritKey =", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyNotEqualTo(String value) {
			addCriterion("secritKey <>", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyGreaterThan(String value) {
			addCriterion("secritKey >", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyGreaterThanOrEqualTo(String value) {
			addCriterion("secritKey >=", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyLessThan(String value) {
			addCriterion("secritKey <", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyLessThanOrEqualTo(String value) {
			addCriterion("secritKey <=", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyLike(String value) {
			addCriterion("secritKey like", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyNotLike(String value) {
			addCriterion("secritKey not like", value, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyIn(List<String> values) {
			addCriterion("secritKey in", values, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyNotIn(List<String> values) {
			addCriterion("secritKey not in", values, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyBetween(String value1, String value2) {
			addCriterion("secritKey between", value1, value2, "secritkey");
			return (Criteria) this;
		}

		public Criteria andSecritkeyNotBetween(String value1, String value2) {
			addCriterion("secritKey not between", value1, value2, "secritkey");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Long value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Long value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Long value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Long value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Long value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Long value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Long> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Long> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Long value1, Long value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Long value1, Long value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andOpentimeIsNull() {
			addCriterion("opentime is null");
			return (Criteria) this;
		}

		public Criteria andOpentimeIsNotNull() {
			addCriterion("opentime is not null");
			return (Criteria) this;
		}

		public Criteria andOpentimeEqualTo(Long value) {
			addCriterion("opentime =", value, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeNotEqualTo(Long value) {
			addCriterion("opentime <>", value, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeGreaterThan(Long value) {
			addCriterion("opentime >", value, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeGreaterThanOrEqualTo(Long value) {
			addCriterion("opentime >=", value, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeLessThan(Long value) {
			addCriterion("opentime <", value, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeLessThanOrEqualTo(Long value) {
			addCriterion("opentime <=", value, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeIn(List<Long> values) {
			addCriterion("opentime in", values, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeNotIn(List<Long> values) {
			addCriterion("opentime not in", values, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeBetween(Long value1, Long value2) {
			addCriterion("opentime between", value1, value2, "opentime");
			return (Criteria) this;
		}

		public Criteria andOpentimeNotBetween(Long value1, Long value2) {
			addCriterion("opentime not between", value1, value2, "opentime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 10 10:22:33 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_server
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 13 10:13:38 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}