package com.login.db.model.area;

import com.login.db.model.area.Area;
import com.login.db.model.area.AreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int countByExample(AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int deleteByExample(AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int insert(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int insertSelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	List<Area> selectByExample(AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	Area selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int updateByExample(@Param("record") Area record, @Param("example") AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int updateByPrimaryKeySelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_area
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	int updateByPrimaryKey(Area record);
}