package com.login.db.model.area;

public class Area {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_area.id
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_area.areaName
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	private String areaname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_area.describle
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	private String describle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_area.isDeleted
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	private Integer isdeleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_area.id
	 * @return  the value of cs_area.id
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_area.id
	 * @param id  the value for cs_area.id
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_area.areaName
	 * @return  the value of cs_area.areaName
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public String getAreaname() {
		return areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_area.areaName
	 * @param areaname  the value for cs_area.areaName
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_area.describle
	 * @return  the value of cs_area.describle
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public String getDescrible() {
		return describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_area.describle
	 * @param describle  the value for cs_area.describle
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public void setDescrible(String describle) {
		this.describle = describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_area.isDeleted
	 * @return  the value of cs_area.isDeleted
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public Integer getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_area.isDeleted
	 * @param isdeleted  the value for cs_area.isDeleted
	 * @mbggenerated  Wed Aug 13 13:02:01 CST 2014
	 */
	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}
}