package com.login.db.model.platform;

import com.login.db.model.platform.Platform;
import com.login.db.model.platform.PlatformExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int countByExample(PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int deleteByExample(PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int insert(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int insertSelective(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    List<Platform> selectByExample(PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    Platform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") Platform record, @Param("example") PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int updateByExample(@Param("record") Platform record, @Param("example") PlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int updateByPrimaryKeySelective(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_platform
     *
     * @mbggenerated Wed Aug 13 10:21:42 CST 2014
     */
    int updateByPrimaryKey(Platform record);
}