package com.login.db.model.clientversion;

public class ClientVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_clientversion.version
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_clientversion.isMust
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    private Integer ismust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_clientversion.isDeleted
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    private Integer isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_clientversion.addtime
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    private Long addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_clientversion.version
     *
     * @return the value of cs_clientversion.version
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_clientversion.version
     *
     * @param version the value for cs_clientversion.version
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_clientversion.isMust
     *
     * @return the value of cs_clientversion.isMust
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public Integer getIsmust() {
        return ismust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_clientversion.isMust
     *
     * @param ismust the value for cs_clientversion.isMust
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public void setIsmust(Integer ismust) {
        this.ismust = ismust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_clientversion.isDeleted
     *
     * @return the value of cs_clientversion.isDeleted
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_clientversion.isDeleted
     *
     * @param isdeleted the value for cs_clientversion.isDeleted
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_clientversion.addtime
     *
     * @return the value of cs_clientversion.addtime
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_clientversion.addtime
     *
     * @param addtime the value for cs_clientversion.addtime
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }
}