package com.login.db.model.clientversion;

import com.login.db.model.clientversion.ClientVersion;
import com.login.db.model.clientversion.ClientVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int countByExample(ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int deleteByExample(ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int deleteByPrimaryKey(String version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int insert(ClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int insertSelective(ClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    List<ClientVersion> selectByExample(ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    ClientVersion selectByPrimaryKey(String version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int updateByExampleSelective(@Param("record") ClientVersion record, @Param("example") ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int updateByExample(@Param("record") ClientVersion record, @Param("example") ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int updateByPrimaryKeySelective(ClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_clientversion
     *
     * @mbggenerated Wed Sep 24 14:20:44 CST 2014
     */
    int updateByPrimaryKey(ClientVersion record);
}