package com.login.db.model.admin;

import com.login.db.model.admin.Admin;
import com.login.db.model.admin.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int countByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int deleteByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int insertSelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	List<Admin> selectByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Admin record,
			@Param("example") AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int updateByExample(@Param("record") Admin record,
			@Param("example") AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int updateByPrimaryKeySelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_admin
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	int updateByPrimaryKey(Admin record);
}