package com.login.db.model.admin;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_admin.id
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_admin.adminName
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	private String adminname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_admin.password
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_admin.security
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	private Integer security;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_admin.isDeleted
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	private Integer isdeleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_admin.id
	 * @return  the value of cs_admin.id
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_admin.id
	 * @param id  the value for cs_admin.id
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_admin.adminName
	 * @return  the value of cs_admin.adminName
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public String getAdminname() {
		return adminname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_admin.adminName
	 * @param adminname  the value for cs_admin.adminName
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public void setAdminname(String adminname) {
		this.adminname = adminname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_admin.password
	 * @return  the value of cs_admin.password
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_admin.password
	 * @param password  the value for cs_admin.password
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_admin.security
	 * @return  the value of cs_admin.security
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public Integer getSecurity() {
		return security;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_admin.security
	 * @param security  the value for cs_admin.security
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public void setSecurity(Integer security) {
		this.security = security;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_admin.isDeleted
	 * @return  the value of cs_admin.isDeleted
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public Integer getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_admin.isDeleted
	 * @param isdeleted  the value for cs_admin.isDeleted
	 * @mbggenerated  Fri Aug 22 11:19:28 CST 2014
	 */
	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}
}