package com.login.db.model.player;

public class Player extends PlayerKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_player.playerId
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	private Long playerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_player.lastLoginTime
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	private Long lastlogintime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_player.playerId
	 * @return  the value of cs_player.playerId
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public Long getPlayerid() {
		return playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_player.playerId
	 * @param playerid  the value for cs_player.playerId
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public void setPlayerid(Long playerid) {
		this.playerid = playerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_player.lastLoginTime
	 * @return  the value of cs_player.lastLoginTime
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public Long getLastlogintime() {
		return lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_player.lastLoginTime
	 * @param lastlogintime  the value for cs_player.lastLoginTime
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public void setLastlogintime(Long lastlogintime) {
		this.lastlogintime = lastlogintime;
	}
}