package com.login.db.model.player;

import com.login.db.model.player.Player;
import com.login.db.model.player.PlayerExample;
import com.login.db.model.player.PlayerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int countByExample(PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int deleteByExample(PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int deleteByPrimaryKey(PlayerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int insert(Player record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int insertSelective(Player record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	List<Player> selectByExample(PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	Player selectByPrimaryKey(PlayerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Player record, @Param("example") PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int updateByExample(@Param("record") Player record, @Param("example") PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int updateByPrimaryKeySelective(Player record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	int updateByPrimaryKey(Player record);

	/**
     * 查找�?��id的player
     */
    Long maxPlayerId(int platformId) ;
}