package com.login.db.model.player;

import java.util.ArrayList;
import java.util.List;

public class PlayerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public PlayerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPlatformidIsNull() {
			addCriterion("platformId is null");
			return (Criteria) this;
		}

		public Criteria andPlatformidIsNotNull() {
			addCriterion("platformId is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformidEqualTo(Integer value) {
			addCriterion("platformId =", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidNotEqualTo(Integer value) {
			addCriterion("platformId <>", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidGreaterThan(Integer value) {
			addCriterion("platformId >", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidGreaterThanOrEqualTo(Integer value) {
			addCriterion("platformId >=", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidLessThan(Integer value) {
			addCriterion("platformId <", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidLessThanOrEqualTo(Integer value) {
			addCriterion("platformId <=", value, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidIn(List<Integer> values) {
			addCriterion("platformId in", values, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidNotIn(List<Integer> values) {
			addCriterion("platformId not in", values, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidBetween(Integer value1, Integer value2) {
			addCriterion("platformId between", value1, value2, "platformid");
			return (Criteria) this;
		}

		public Criteria andPlatformidNotBetween(Integer value1, Integer value2) {
			addCriterion("platformId not between", value1, value2, "platformid");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userId like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userId not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andPlayeridIsNull() {
			addCriterion("playerId is null");
			return (Criteria) this;
		}

		public Criteria andPlayeridIsNotNull() {
			addCriterion("playerId is not null");
			return (Criteria) this;
		}

		public Criteria andPlayeridEqualTo(Long value) {
			addCriterion("playerId =", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridNotEqualTo(Long value) {
			addCriterion("playerId <>", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridGreaterThan(Long value) {
			addCriterion("playerId >", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridGreaterThanOrEqualTo(Long value) {
			addCriterion("playerId >=", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridLessThan(Long value) {
			addCriterion("playerId <", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridLessThanOrEqualTo(Long value) {
			addCriterion("playerId <=", value, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridIn(List<Long> values) {
			addCriterion("playerId in", values, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridNotIn(List<Long> values) {
			addCriterion("playerId not in", values, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridBetween(Long value1, Long value2) {
			addCriterion("playerId between", value1, value2, "playerid");
			return (Criteria) this;
		}

		public Criteria andPlayeridNotBetween(Long value1, Long value2) {
			addCriterion("playerId not between", value1, value2, "playerid");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIsNull() {
			addCriterion("lastLoginTime is null");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIsNotNull() {
			addCriterion("lastLoginTime is not null");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeEqualTo(Long value) {
			addCriterion("lastLoginTime =", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotEqualTo(Long value) {
			addCriterion("lastLoginTime <>", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeGreaterThan(Long value) {
			addCriterion("lastLoginTime >", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeGreaterThanOrEqualTo(Long value) {
			addCriterion("lastLoginTime >=", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeLessThan(Long value) {
			addCriterion("lastLoginTime <", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeLessThanOrEqualTo(Long value) {
			addCriterion("lastLoginTime <=", value, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeIn(List<Long> values) {
			addCriterion("lastLoginTime in", values, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotIn(List<Long> values) {
			addCriterion("lastLoginTime not in", values, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeBetween(Long value1, Long value2) {
			addCriterion("lastLoginTime between", value1, value2, "lastlogintime");
			return (Criteria) this;
		}

		public Criteria andLastlogintimeNotBetween(Long value1, Long value2) {
			addCriterion("lastLoginTime not between", value1, value2, "lastlogintime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cs_player
	 * @mbggenerated  Thu Aug 21 18:39:13 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cs_player
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 13 10:14:04 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}